name: affogato_editor
description: "A feature-rich and extensible code workspace for Flutter Web."
version: 0.3.0
homepage: https://affogato.obsivision.com
repository: https://github.com/Affogato-Project/Affogato-Editor
issue_tracker: https://github.com/Affogato-Project/Affogato-Editor/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  re_highlight: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/IBM_Plex_Mono/IBMPlexMono-SemiBold.ttf
          weight: 600
    - family: SetiUiIcons
      fonts:
        - asset: assets/Seti_UI_Icons/SetiUiIcons.ttf