name: affogato_editor
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  affogato_core:
    path: ../AffogatoCore
  re_highlight: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/IBM_Plex_Mono/IBMPlexMono-SemiBold.ttf
          weight: 600
    - family: SetiUiIcons
      fonts:
        - asset: assets/Seti_UI_Icons/SetiUiIcons.ttf